[chore] Handling of NullPointerException in AuthorizationManagerActivity
pagopa/io-react-native-login-utils pull request #17
Opened 2024-09-25 14:30 UTC by Vangaorth

## Short description
This PR handles a case where a `null` instance of the `authIntent` crashes the application.
It also removes references to the `authorizationPromise` after it has been either resolved or rejected.

## List of changes proposed in this pull request
- added a catch to the method that causes the crash
- removal of `authorizationPromise` references

## How to test
Make sure that static checks do succeed and that InApp Browser flows (in the example app) succeed

2024-09-25 15:32 UTC, shadowsheep1 requested changes

2024-09-25 15:32 UTC, shadowsheep1 commented on android/src/main/java/com/iologinutils/AuthorizationManagerActivity.kt
> +      IoLoginUtilsModule.authorizationPromise = null
What about wrap this logic inside an utility function? For example

```ts
fun rejectAndClearAuthorizationPromise(errorCode: String, errorType: IoLoginError.Type) {
    IoLoginUtilsModule.authorizationPromise?.reject(
        errorCode,
        generateErrorObject(errorType)
    )
    IoLoginUtilsModule.authorizationPromise = null
}
```
and use it all places where we are rejecting the `promise` and resetting a `null` the `authorizationPromise`?

What do you think?

2024-10-01 12:33 UTC, Vangaorth commented on android/src/main/java/com/iologinutils/AuthorizationManagerActivity.kt
> +      IoLoginUtilsModule.authorizationPromise = null
Yeah, let's do it

2024-10-01 12:53 UTC, Vangaorth commented on android/src/main/java/com/iologinutils/AuthorizationManagerActivity.kt
> +      IoLoginUtilsModule.authorizationPromise = null
Done in [f53aa8f](https://github.com/pagopa/io-react-native-login-utils/pull/17/commits/f53aa8fe7d3ad2033a5ef7132b660b153a13db2f)

2024-10-02 08:14 UTC, shadowsheep1 approved these changes
LGTM

2024-10-02 08:18 UTC, merged